// <auto-generated />
using System;
using CTrace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CTrace.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211205184532_contactupdate3")]
    partial class contactupdate3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CTrace.Models.Contact", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("contact_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CreatedByuser_id")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryUseruser_id")
                        .HasColumnType("int");

                    b.Property<int>("SecondUseruser_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("contact_created")
                        .HasColumnName("contact_time")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("CreatedByuser_id");

                    b.HasIndex("PrimaryUseruser_id");

                    b.HasIndex("SecondUseruser_id");

                    b.ToTable("tab_contact");
                });

            modelBuilder.Entity("CTrace.Models.Detection", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("detection_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreatedByuser_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnName("detection_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CreatedByuser_id");

                    b.HasIndex("user_id");

                    b.ToTable("tab_detection");
                });

            modelBuilder.Entity("CTrace.Models.Notification", b =>
                {
                    b.Property<Guid>("notif_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("notif_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("notif_created")
                        .HasColumnName("notif_created")
                        .HasColumnType("datetime2");

                    b.Property<string>("notif_redirect")
                        .HasColumnName("notif_redirect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notif_text")
                        .IsRequired()
                        .HasColumnName("notif_text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("notif_useruser_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("notif_ṛead")
                        .HasColumnName("notif_ṛead")
                        .HasColumnType("datetime2");

                    b.HasKey("notif_id");

                    b.HasIndex("notif_useruser_id");

                    b.ToTable("tab_notification");
                });

            modelBuilder.Entity("CTrace.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("user_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("user_failcount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("user_failcount")
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("0");

                    b.Property<string>("user_fname")
                        .IsRequired()
                        .HasColumnName("user_fname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("user_isadmin")
                        .IsRequired()
                        .HasColumnName("user_isadmin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("user_lastlogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("user_lastlogin")
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("user_lname")
                        .HasColumnName("user_lname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnName("user_mobile")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("user_pass")
                        .IsRequired()
                        .HasColumnName("user_pass")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("user_salt")
                        .IsRequired()
                        .HasColumnName("user_salt")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("user_id");

                    b.HasIndex("user_name")
                        .IsUnique();

                    b.ToTable("tab_users");

                    b.HasData(
                        new
                        {
                            user_id = 1,
                            user_failcount = (byte)0,
                            user_fname = "Admin",
                            user_isadmin = true,
                            user_lastlogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            user_name = "admin",
                            user_pass = "7yqhZk6N5bvBDekEL0wq8cL2nbYtZChYu9BJqSLXpuA=",
                            user_salt = "SxOURuX3iCNyJmm2RpfIHg=="
                        });
                });

            modelBuilder.Entity("CTrace.Models.Contact", b =>
                {
                    b.HasOne("CTrace.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByuser_id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CTrace.Models.User", "PrimaryUser")
                        .WithMany()
                        .HasForeignKey("PrimaryUseruser_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CTrace.Models.User", "SecondUser")
                        .WithMany()
                        .HasForeignKey("SecondUseruser_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("CTrace.Models.Detection", b =>
                {
                    b.HasOne("CTrace.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByuser_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CTrace.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("CTrace.Models.Notification", b =>
                {
                    b.HasOne("CTrace.Models.User", "notif_user")
                        .WithMany()
                        .HasForeignKey("notif_useruser_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
